# Generated by Django 5.2.9 on 2025-12-13 02:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_sets', to='notes.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('ease_factor', models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(1.3)])),
                ('review_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('last_studied', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.flashcardset')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('simple', 'Simple'), ('spaced', 'Spaced Repetition')], default='simple', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cards_studied', models.IntegerField(default=0)),
                ('cards_correct', models.IntegerField(default=0)),
                ('flashcard_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='flashcards.flashcardset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['user', '-updated_at'], name='flashcards__user_id_c456d0_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardset',
            index=models.Index(fields=['user', 'category'], name='flashcards__user_id_4b9b77_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['flashcard_set', 'next_review'], name='flashcards__flashca_c413c1_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['flashcard_set'], name='flashcards__flashca_83dc72_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['next_review'], name='flashcards__next_re_ce9307_idx'),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.CheckConstraint(condition=models.Q(('ease_factor__gte', 1.3)), name='ease_factor_minimum'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', '-started_at'], name='flashcards__user_id_1bc1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'flashcard_set'], name='flashcards__user_id_e12a19_idx'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(('cards_correct__lte', models.F('cards_studied'))), name='cards_correct_le_cards_studied'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(('cards_studied__gte', 0)), name='cards_studied_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(('cards_correct__gte', 0)), name='cards_correct_non_negative'),
        ),
    ]
